### PR TITLE
updated roadmap

### PR DESCRIPTION
**Pull request by aagarwal1012**
The spinners are taken from [loadingio](https://github.com/loadingio/css-spinner/).

### CODE REVIEW

**Comment by jogboms** [comment]
Nice.
You know what @aagarwal1012, how about we create an enhancement issue listing these animations as checklist right now. Then we can use that to get feedback on what the community would need and then we can implement accordingly.
This way we can do housekeeping while keeping things simple and sweet and giving others even more space to contribute and vote on what should stay and what shouldn't.
What do you say?

**Comment by aagarwal1012** [comment]
Your idea is good 👍  but I want to add some more in the list. We have many more spinners that could be put in the enhancement issue. Hope you won't mind.

**Comment by jogboms** [comment]
Okay. I'm actually just trying to mirror inspiration from the original idea so it doesn't get too clunky. Most likely, anyone installing the library would be only interested in using just one. Just trying to make sure the list grows according to community needs and very organic and not just because we can make them. Do you get me?

**Comment by aagarwal1012** [comment]
OK! I agree with your idea but can you merge the Rotating plane and Rotating circle and in the place of anyone please put my Pumping heart spinner as I have spent a lot of time in making it.

**Comment by jogboms** [comment]
Oh, okay. That makes sense. Will do so. Thanks for understanding. 😄

**Comment by aagarwal1012** [comment]
Thanks! 👍

**Comment by aagarwal1012** [comment]
Please merge the commits.

**Comment by jogboms** [comment]
Will do. Was a bit swamped with some other tasks, haven't had time to test. Would do so today.

**Comment by aagarwal1012** [comment]
Now you can merge those commits. I have added pumping heart in place of rotating plane.

**Pull request merged**
