### PR TITLE
refactor: increase code quality

### PR DESCRIPTION
**Pull request by OutdatedGuy**
**No code logic is changed, only styling and formatting is done**

### Changes

- updated `.gitignore` file with the latest flutter template. (This removes unnecessary root level `pubspec.lock` file)
- formatted code with dart standards using `dart fix --apply` and `dart format .`
  Screenshot 2023-05-09 at 2 14 41 AM

### CODE REVIEW

**Comment by OutdatedGuy** [comment]
@jogboms, can you please review this?

**Comment by jogboms** [comment]
Hey @OutdatedGuy
Could you set the lineWrap width to 120?

**Comment by OutdatedGuy** [comment]
> Could you set the lineWrap width to 120?

@jogboms Sorry, I have no idea on how to do that.

**Comment by jogboms** [comment]
@OutdatedGuy 
dart format -l 120 lib -l 120 example

**Comment by OutdatedGuy** [comment]
@jogboms, done. Please check.

**Review by jogboms — APPROVED** [review]

**Pull request merged**
