### PR TITLE
The DualRing and HourGlass do not require asset files.

### PR DESCRIPTION
**Pull request by CaiJingLong**
Replace the image file with CustomPainter.
Then The DualRing and HourGlass do not require asset files.

### CODE REVIEW

**Comment by jogboms** [comment]
Wow! This is cool @CaiJingLong 

@aagarwal1012 can you take a look here?

**Review by aagarwal1012 — CHANGES_REQUESTED** [review]
@CaiJingLong Great Work 😄, but before merging fix all the `formatting issues`.

**Comment by CaiJingLong** [comment]
I use vscode auto save to formatted code. 
Because I modified the default number of single line characters from 80 to 160, so maybe my code looks different from the project. 
If the code has a formatting problem, please help me to fix it.

**Comment by jogboms** [comment]
Nice work @CaiJingLong. 
Are we good with this, @aagarwal1012 so i can push a new release.

**Review by aagarwal1012 — APPROVED** [review]

**Comment by aagarwal1012** [comment]
@CaiJingLong Thanks 👍
@jogboms You can push the new release.

**Pull request merged**
